CREATE TABLE IF NOT EXISTS "AlbankTask"
(
    "Id" integer NOT NULL,
    "Title" character varying(128),
    "Description" character varying(1024),
    "DueDate" timestamp without time zone NOT NULL,
    "CreatedOn" timestamp without time zone NOT NULL,
    "CompletedOn" timestamp without time zone,
    "Status" integer NOT NULL,
    "IsRecycled" boolean DEFAULT false NOT NULL
);

ALTER TABLE "AlbankTask" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlbankTask_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO "AlbankTask" ("Title","Description","DueDate","CreatedOn","CompletedOn","Status","IsRecycled") VALUES
	 ('Покормить кота','','2022-11-08 00:00:00','2022-11-07 23:48:00','2022-11-08 00:00:00',0,false),
	 ('Досмотреть аниме','Семья шпиона','2022-12-24 00:00:00','2022-11-08 00:07:14',NULL,1,false),
	 ('Сделать тестовое задание','Очень страшно, очень страшно. Мы не знаем что это такое, если бы мы знали что это такое, мы не знаем что это такое','2022-11-10 00:00:00','2022-11-08 00:04:07','2022-11-09 00:00:00',2,false);