/connect albanktododb

CREATE TABLE "AlbankTask"
(
    "Id" integer NOT NULL,
    "Title" character varying(128),
    "Description" character varying(1024),
    "DueDate" timestamp without time zone NOT NULL,
    "CreatedOn" timestamp without time zone NOT NULL,
    "CompletedOn" timestamp without time zone,
    "Status" integer NOT NULL,
    "IsRecycled" boolean DEFAULT false NOT NULL
);

ALTER TABLE "AlbankTask" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlbankTask_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

INSERT INTO "AlbankTask" ("Title","Description","DueDate","CreatedOn","CompletedOn","Status","IsRecycled") VALUES
	 ('Покормить кота','','2022-11-08 00:00:00','2022-11-07 23:48:00.601109',NULL,0,false),
	 ('Научиться какать','Саа5ын ыраас дуо??','2022-12-31 00:00:00','2022-11-08 00:02:35.815914',NULL,0,false),
	 ('Сделать тестовое задание','Очень страшно, очень страшно. Мы не знаем что это такое, если бы мы знали что это такое, мы не знаем что это такое','2022-11-10 00:00:00','2022-11-08 00:04:07.700333',NULL,0,false),
	 ('Сходить за хлебом','Булку белого ЯХК','2022-11-08 00:00:00','2022-11-08 00:07:14.562065',NULL,0,false),
	 ('Закончить учебу','Похуй как','2023-06-01 00:00:00','2022-11-08 00:08:08.511951',NULL,0,false),
	 ('Купить память','DDR4 2x16GB 3200MHz','2023-01-01 00:00:00','2022-11-08 00:09:14.198488',NULL,0,false),
	 ('Купить второй монитор','1080p 144+Hz 24inch','2023-01-01 00:00:00','2022-11-08 00:11:04.378196',NULL,0,false),
	 ('Заплатить за инет','1300 КАРЛ','2022-11-21 00:00:00','2022-11-08 00:11:56.078271',NULL,0,false),
	 ('Убраться в доме','','2022-11-08 00:00:00','2022-11-08 00:12:25.628545',NULL,0,false),
	 ('Сделать срс4 по пенсионеру','сложна','2022-11-11 00:00:00','2022-11-08 00:13:48.001394',NULL,0,false);
INSERT INTO "AlbankTask" ("Title","Description","DueDate","CreatedOn","CompletedOn","Status","IsRecycled") VALUES
	 ('Не забыть позавтракать','ы','2022-11-08 00:00:00','2022-11-08 00:14:57.969906',NULL,0,false),
	 ('Создать отдельный класс для вызова saveChanges()','чтобы не было через чур много ''new IDbContext()''','2022-11-10 00:00:00','2022-11-08 00:05:50.075823',NULL,1,false),
	 ('Принять душ','Контрастный','2022-11-09 00:00:00','2022-11-08 00:13:17.847683','2022-11-09 00:34:04.052865',2,false);